### PR TITLE
Fixed Issue #107

### PR DESCRIPTION
**Pull request by ShubhamAXS19**
<h2>Replace Agro Millets with FreshNest #107</h2>

<h3>Description</h3>
Fix issue #107
Screenshot 2023-10-02 at 1 36 58 PM

### CODE REVIEW

**Comment by AmanNegi** [comment]
Great work @ShubhamAXS19, could you also fix this throughout the project? I noticed it is still Agro Millets in some `README.md` files. Feel free to do a global search, and you should end with appropriate results.

**Comment by ShubhamAXS19** [comment]
Sure thing.
i will it asap and push the code

**Comment by AmanNegi** [comment]
@ShubhamAXS19 Any updates on this?

**Comment by ShubhamAXS19** [comment]
it is done from my end 
forgot to inform you

**Review by AmanNegi — APPROVED** [review]
LGTM!

**Pull request merged**
