### PR TITLE
Implemented Client-Side Filtering for Shop Page

### PR DESCRIPTION
**Pull request by Chirayu31**
Solves issue #121

### CODE REVIEW

**Review by AmanNegi — CHANGES_REQUESTED** [review]
Currently, when we render the ShopItem we use the index as a key. This doesn't allow the list to be refreshed, as we are using indices to uniquely determine. Whereas, the index always remains the same. To re-render we should ensure to pass a unique key to each element, which would be `e._id`.

**Comment by Chirayu31** [comment]
Working on it

**Comment by Chirayu31** [comment]
Hey did the changes!

**Review by AmanNegi — APPROVED** [review]

**Comment by AmanNegi** [comment]
Great work @Chirayu31! Works as expected now, merging it right away. 🚀

**Pull request merged**
