### PR TITLE
Add Loading and Validation in Login/SignUp

### PR DESCRIPTION
**Pull request by ayobamiseun**
I also repositioned the function for both login and signup.

Fixes: #123

### CODE REVIEW

**Comment by AmanNegi** [comment]
@ayobamiseun It's always preferred to create a new branch for every PR you make, it's not suggested to use the `main` branch. Feel free to create a new PR from a separate branch.

**Comment by AmanNegi** [comment]
@ayobamiseun you should create your branch let's say you are working on adding a loading indicator on the Loading/SignUp page. You could name your branch as `auth-add-suspense` or `auth-add-loading`.  Once you are done with this issue, the branch will be merged with the main branch and then if you work on some new issue you should create a new branch appropriately.

Learn more: https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Review by sumit639-code — COMMENTED** [review]
the changes are good but instead of giving only check if the login length are filled or not we should check if it is genuine or not

**Comment by ayobamiseun** [comment]
> the changes are good but instead of giving only check if the login length are filled or not we should check if it is genuine or not

that will be coming from an api. if i can get the status code i can also handle that. also check if an account already exists or not.

**Comment by AmanNegi** [comment]
> the changes are good but instead of giving only check if the login length are filled or not we should check if it is genuine or not

@sumit639-code sounds appropriate to me. We can use `formik` for this.

**Comment by AmanNegi** [comment]
> that will be coming from an api. if i can get the status code i can also handle that. also check if an account already exists or not.

@ayobamiseun We do handle errors coming from the APIs and show them as an error. What @sumit639-code meant to say was that we should add a layer of validation in the front end itself. I guess, we can use Formik to achieve that easily.

**Comment by AmanNegi** [comment]
Shifted to #130.

**Pull request closed without merging**
