### PR TITLE
Fix #185 : Remove timer's live property

### LINKED ISSUE #185: fix: remove timer's live property
## Description 🤷‍♂️

After adding a product as a farmer, we are redirected to the home page. On the home page, we see a grid of items with the time they were added. However, the newly added item shows a live timer such as "1, 2, 3 seconds ago" which is unexpected and seems like an error.

We want to remove the live behaviour of the time shown.

### Demo 📽️

https://github.com/AmanNegi/FreshNest/assets/37607224/7fb7239f-5b60-470a-876d-2db8160ae2ad

### Affected Files 🗃️

- frontend/react/src/components/ShopItem.jsx

### PR DESCRIPTION
**Pull request by MohitKambli**
Hello,
Hope you're doing well.
In order to solve issue #185, I have simply added the `live` property to the _**TimeAgo**_ component and set it to `false`.
The reason for doing this is to remove the live timer which actually looked like _"1, 2, 3 seconds ago"_ before introducing the mentioned property and setting it to `false`.
The default value of this property is `true`.
For more details regarding the property and react-timeago component, one can refer this [link]([https://github.com/nmn/react-timeago?tab=readme-ov-file](https://github.com/nmn/react-timeago?tab=readme-ov-file#live-optional)).
If at all there is anything required from my end, then do let me know.
Sincere apologies for my mistakes if you find any.

Thanks and Regards,
Mohit Kambli

### CODE REVIEW

**Comment by AmanNegi** [comment]
Love the PR description. Thanks a lot for taking out your time and contributing to FreshNest.

> Feel free to come back for more issues, or if you find any issues while using the platform feel free to lodge an issue anytime. ✨🚀

**Comment by MohitKambli** [comment]
Hello @AmanNegi,
I pulled the latest changes and pushed the code changes back.
Does that look fine to you?

Regards,
Mohit Kambli

**Comment by AmanNegi** [comment]
@MohitKambli Could you squash the 4 commits into one commit.

- Guide: https://www.freecodecamp.org/news/git-squash-commits/

**Comment by MohitKambli** [comment]
Hello @AmanNegi,
I tried to squash the commits into one by following the rebase process.
I am not sure if that actually happened or no.
Could you please help me with that?
Sincere apologies for causing the trouble.
I need to work on Git properly.

Regards,
Mohit Kambli

**Pull request closed without merging**
