### PR TITLE
added refreshIndicator

### PR DESCRIPTION
**Pull request by Sandesh-03**
@AmanNegi 

 issue solved #150 

added the refresh to pull function

### CODE REVIEW

**Comment by AmanNegi** [comment]
Hey @Sandesh-03 could you attach a demo video, so that I can get through this ASAP.

**Comment by Sandesh-03** [comment]
OK, here is the video

https://github.com/AmanNegi/FreshNest/assets/102364055/b50e943c-a40b-41b3-910c-f8b4b7c717eb

**Comment by Sandesh-03** [comment]
hey @AmanNegi  is this ok ?

**Comment by AmanNegi** [comment]
Remove the changes in `pubspec.lock` and push the file. I'll merge this right away :)

**Comment by Sandesh-03** [comment]
sure

**Comment by Sandesh-03** [comment]
- removed the changes in pubspec.lock

**Pull request merged**
