### PR TITLE
Resolves issue #133 fixes explore products image cutoff

### PR DESCRIPTION
**Pull request by Codensity30**
Added text over the image to make it responsive.
image

### CODE REVIEW

**Comment by AmanNegi** [comment]
Nice work! @Codensity30. Looks good but the orientation of other things looks off.

### Earlier
image

--- 
### Now
image

Could you fix this issue, with the orientation of the products? Try to maintain the aspect ratio, as the image should not span across the whole height.

**Comment by Codensity30** [comment]
I actually wasn't able to see the products that's the reason why the orientation seems to be off.
image

Though I've started the backend as per the guidelines and the request to fetch products is made to the backend, I've verified this as the useEffect in the component logs a statement.

```
useEffect(() => {
    getFourItems().then((e) => {
      setProducts(e);
      console.log("Set List to ", e);
    });
  }, []);
```
and this is the log
image

I need to fix this first only that I can work on the orientation.

**Comment by AmanNegi** [comment]
That's because no product is added to your local host yet. Feel free to use the remote development server:

```
VITE_API_URL="https://agromillets.adaptable.app/api"
```

**Comment by AmanNegi** [comment]
Looks great, just a little more margin from the left side, so that the spacing from the left equals the spacing after the products (towards the right). The image height should be equal to the height taken by the products.

image

Earlier the spacing was equal from left-right and the product image was medium-sized and somewhat square.

#### Reference
image

**Comment by Codensity30** [comment]
Finally, I fixed this height disorder, it took much longer than expected because you have used fixed sizes rather than tailwind classes which I've fixed various classes, styling, and all.
image

**Comment by AmanNegi** [comment]
@Codensity30  Thanks a lot for cleaning and fixing things up! 💚 Merging your PR right away.

> ~ Keep Contributing ~

**Pull request merged**
