### PR TITLE
added splash screen and logo for the app

### PR DESCRIPTION
**Pull request by Sandesh-03**
@AmanNegi 
I have added a Splash screen and added logo for the app Please check it

### CODE REVIEW

**Comment by AmanNegi** [comment]
Could you share a demo recording showing the splash screen?

**Comment by AmanNegi** [comment]
Also always mention the issue you are fixing in issue description.

**Comment by Sandesh-03** [comment]
Sure.

**Comment by Sandesh-03** [comment]
issues solved  #143 
also added a logo  for app
here is the output

https://github.com/AmanNegi/FreshNest/assets/102364055/16bd59cc-2ec1-4576-a31f-ff78d1402413

**Comment by AmanNegi** [comment]
@Sandesh-03, we appreciate your willingness to contribute, but it's essential to respect the assignment of issues to avoid time wastage and duplication of effort. In this case, since you weren't the assigned contributor, we kindly request that you refrain from working on this issue. Your contributions are valuable, and we encourage you to focus your efforts on issues that align with your expertise and current assignments. 

We will appropriately manage and close your pull request to maintain the efficiency of our open-source project. Thank you for your understanding and continued support.

**Comment by AmanNegi** [comment]
@Sandesh-03, we appreciate your willingness to contribute, but it's essential to respect the assignment of issues to avoid time wastage and duplication of effort. In this case, since you weren't the assigned contributor, we kindly request that you refrain from working on this issue. Your contributions are valuable, and we encourage you to focus your efforts on issues that align with your expertise and current assignments. 

We will appropriately manage and close your pull request to maintain the efficiency of our open-source project. Thank you for your understanding and continued support.

**Pull request closed without merging**
