### PR TITLE
fix: Fix content stretching on 4k screens for sign-up and login

### PR DESCRIPTION
**Pull request by dipaksinha1**
**Fixes**
#141 

I have established a maximum width for both the login and signup pages. The content is centered, providing a similar stretched appearance as seen in the login/signup pages of LinkedIn.

1.Login Page
Before
image

After 
image

2.Signup Page
Before
image

After
image

### CODE REVIEW

**Comment by dipaksinha1** [comment]
Hi @AmanNegi , PR is ready for review.

**Comment by dipaksinha1** [comment]
Hi @AmanNegi , I hope you're doing well. Just wanted to check in and remind you about the pull request I shared earlier.

**Comment by AmanNegi** [comment]
Sorry for the late response @dipaksinha1. Have been busy the last week, looking into this right away.

**Review by AmanNegi — APPROVED** [review]
LGTM!

**Comment by AmanNegi** [comment]
Thanks a lot for your contribution @dipaksinha1! ✨

**Pull request merged**
